# Generated by Django 6.0.5 on 2026-05-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=150)),
                ('mensagem', models.TextField()),
                ('lido', models.BooleanField(default=False)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('categoria', models.CharField(choices=[('linguagem', 'Linguagem'), ('framework', 'Framework'), ('banco', 'Banco de Dados'), ('ferramenta', 'Ferramenta'), ('soft', 'Soft Skill')], default='linguagem', max_length=20)),
                ('nivel', models.PositiveIntegerField(default=80)),
                ('icone', models.CharField(blank=True, max_length=60)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['categoria', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('tecnologias', models.CharField(help_text='ex: Python, Django, MySQL', max_length=200)),
                ('url_github', models.URLField(blank=True, verbose_name='Link GitHub')),
                ('url_demo', models.URLField(blank=True, verbose_name='Link Demo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='projetos/')),
                ('categoria', models.CharField(choices=[('web', 'Web'), ('api', 'API / Backend'), ('bot', 'Bot / Automação'), ('dados', 'Dados'), ('outro', 'Outro')], default='web', max_length=20)),
                ('destaque', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SobreMim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo', models.CharField(default='Desenvolvedor Python & Django', max_length=200)),
                ('bio', models.TextField()),
                ('bio_curta', models.CharField(max_length=300)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('localizacao', models.CharField(blank=True, default='Niterói, RJ', max_length=100)),
                ('curriculo_pdf', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sobre Mim',
                'verbose_name_plural': 'Sobre Mim',
            },
        ),
    ]
